In [13]:
import math
def basic_sigmoid(x):
    """
    compute sigmoid of x
    """
    s = 1/(1+math.exp(-x))
    
    return s
print(basic_sigmoid(3));

0.9525741268224334


if x=(x1,x2,...,xn) is a row vector then np.exp(x) will apply the exponential function to every element of x

In [14]:
import numpy as np 
x = np.array([1,2,3])
s = np.exp(x) 
print(s)

[ 2.71828183  7.3890561  20.08553692]


if x is a vector, then a Python operation such as s=x+3 or s=1x will output s as a vector of the same size as x.

In [15]:
x = np.array([1, 2, 3])
print (x + 3)

[4 5 6]


In [26]:

s = 3
def numpy_sigmoid(x):
    s = 1/(1+np.exp(-x))
    
    return s
x = np.array([1,2,3])
print(numpy_sigmoid(x))

[0.73105858 0.88079708 0.95257413]


In [28]:
def sigmoid_derivative(x):
    ds = numpy_sigmoid(x)*(1-numpy_sigmoid(x))
    return ds
x = np.array([1,2,3])
print(sigmoid_derivative(x))

[0.19661193 0.10499359 0.04517666]


In [38]:
#测试shape
x = np.array([1,2,3])
y = np.array([[1,2,3]])
print(x.shape)
print(y.shape)
print(np.dot(x,x.T))
print(np.dot(y,y.T))
print(x[0])
print(y[0])

(3,)
(1, 3)
14
[[14]]
1
[1 2 3]


In [43]:
def image2vector(image):
    v = image.reshape(image.shape[0]*image.shape[1]*image.shape[2],1)
    return v

image = np.array([[[ 0.67826139,  0.29380381],
        [ 0.90714982,  0.52835647],
        [ 0.4215251 ,  0.45017551]],

       [[ 0.92814219,  0.96677647],
        [ 0.85304703,  0.52351845],
        [ 0.19981397,  0.27417313]],

       [[ 0.60659855,  0.00533165],
        [ 0.10820313,  0.49978937],
        [ 0.34144279,  0.94630077]]])
print("image2vector(image) = "+str(image2vector(image)))

image2vector(image) = [[0.67826139]
 [0.29380381]
 [0.90714982]
 [0.52835647]
 [0.4215251 ]
 [0.45017551]
 [0.92814219]
 [0.96677647]
 [0.85304703]
 [0.52351845]
 [0.19981397]
 [0.27417313]
 [0.60659855]
 [0.00533165]
 [0.10820313]
 [0.49978937]
 [0.34144279]
 [0.94630077]]


In [47]:
#Normalizing rows
def normalizeRows(x):
    #axis=1 对行向量求二范数  keepdims=true 保证数组仍是二位
    x_norm = np.linalg.norm(x,axis=1,keepdims=True)
    s = x/x_norm
    return s

x = np.array([[0,3,4],[1,6,4]])
print(normalizeRows(x))

[[0.         0.6        0.8       ]
 [0.13736056 0.82416338 0.54944226]]


In [51]:
#广播(Broadcasting) 练习
def softmax(x):
    x_norm = np.sum(np.exp(x),axis=1,keepdims=True)
    x = np.exp(x)/x_norm
    return x

x = np.array([[9,2,5,0,0],[7,5,0,0,0]])
print("softmax(x):"+str(softmax(x)))

softmax(x):[[9.80897665e-01 8.94462891e-04 1.79657674e-02 1.21052389e-04
  1.21052389e-04]
 [8.78679856e-01 1.18916387e-01 8.01252314e-04 8.01252314e-04
  8.01252314e-04]]


In [87]:
#vectorizatin（向量化）
import time
x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]

### ----------------点乘的for循环实现形式--------------------￥####
tic = time.process_time()
dot = 0 
for i in range(len(x1)):
    dot+=x1[i]*x2[i]
    
toc = time.process_time()

print("dot = "+str(dot)+"time:"+str(1000*(toc-tic)))

###---------------------向量相乘的for循环实现-------------------###

tic = time.process_time()

outer = np.zeros((len(x1),len(x2)))


for i in range(len(x1)):
    for j in range(len(x2)):
        outer[i,j] = x1[i]*x2[j]
                 
toc=time.process_time()
print ("outer = \n" + str(outer) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

###-------------------------元素逐个相乘的for实现-----------------------------###
tic = time.process_time()
mul = np.zeros(len(x1))
for i in range(len(x1)):
    mul[i] = x1[i]*x2[i]
toc = time.process_time()
print ("elementwise multiplication = " + str(mul) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### --------矩阵相乘的for循环实现-------------------###
w = np.random.rand(3,len(x1))  #生成随机的3*len(x1) 的数组
tic = time.process_time()
gdot = np.zeros(w.shape[0])
for i in range(w.shape[0]):
        for j in range(len(x1)):
                gdot[i]+=w[i,j]*x1[j]
toc = time.process_time()
print("gdot:\n"+str(gdot)+"\n time:"+str(toc-tic))


dot = 278time:0.0
outer = 
[[81. 18. 18. 81.  0. 81. 18. 45.  0.  0. 81. 18. 45.  0.  0.]
 [18.  4.  4. 18.  0. 18.  4. 10.  0.  0. 18.  4. 10.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [63. 14. 14. 63.  0. 63. 14. 35.  0.  0. 63. 14. 35.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [81. 18. 18. 81.  0. 81. 18. 45.  0.  0. 81. 18. 45.  0.  0.]
 [18.  4.  4. 18.  0. 18.  4. 10.  0.  0. 18.  4. 10.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
 ----- Computation time = 0

In [89]:
x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]

### VECTORIZED DOT PRODUCT OF VECTORS ###
tic = time.process_time()
dot = np.dot(x1,x2)
toc = time.process_time()
print ("dot = " + str(dot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### VECTORIZED OUTER PRODUCT ###
tic = time.process_time()
outer = np.outer(x1,x2)
toc = time.process_time()
print ("outer = " + str(outer) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### VECTORIZED ELEMENTWISE MULTIPLICATION ###
tic = time.process_time()
mul = np.multiply(x1,x2)
toc = time.process_time()
print ("elementwise multiplication = " + str(mul) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### VECTORIZED GENERAL DOT PRODUCT ###
tic = time.process_time()
dot = np.dot(w,x1)
toc = time.process_time()
print ("gdot = " + str(dot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

dot = 278
 ----- Computation time = 0.0ms
outer = [[81 18 18 81  0 81 18 45  0  0 81 18 45  0  0]
 [18  4  4 18  0 18  4 10  0  0 18  4 10  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [63 14 14 63  0 63 14 35  0  0 63 14 35  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [81 18 18 81  0 81 18 45  0  0 81 18 45  0  0]
 [18  4  4 18  0 18  4 10  0  0 18  4 10  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]
 ----- Computation time = 0.0ms
elementwise multiplication = [81  4 10  0  0 63 10  0  0  0 81  4 25  0  0]
 ----- Computation time = 0.0ms
gdot = [22.10241525 14.32386316 22.74275943]
 ----- Computation time = 0.0ms


In [110]:
#损失函数L1的实现
def L1(yhat,y):
    s = np.sum(np.abs(yhat-y))
    return s

yhat = np.array([0.9,0.2,0.1,0.40,.9])
y = np.array([1,0,0,1,1])
print("L1 = " + str(L1(yhat,y)))

# 损失函数L2实现
def L2(yhat,y):
    s = np.sum(np.power((y-yhat),2))
    return s

print("L2 = " + str(L2(yhat,y)))


L1 = 1.1
L2 = 0.43
